/* 
 *  $Id: paths.h.in,v 1.6 2004/04/11 12:36:02 mbroek Exp $
 *
 *  Autogenerated by configure 
 */

/*
 * Paths to archivers
 */
#define _PATH_COMPRESS  "/usr/bin/compress"
#define _PATH_GZIP      "/usr/bin/gzip"
#define _PATH_ARC	"/usr/bin/arc"
#define _PATH_NOMARCH   ""
#define	_PATH_ARJ	"/usr/bin/arj"
#define	_PATH_UNARJ	"/usr/bin/unarj"
#define	_PATH_LHA	"/usr/bin/lha"
#define	_PATH_RAR	"/usr/bin/rar"
#define	_PATH_UNRAR	""
#define	_PATH_TAR	"/usr/bin/tar"
#define	_PATH_ZIP	"/usr/bin/zip"
#define	_PATH_UNZIP	"/usr/bin/unzip"
#define	_PATH_ZOO	"/usr/bin/zoo"
#define _PATH_HA	""



/*
 * Path to convert, to create thumbnails.
 */
#define	_PATH_CONVERT	"/usr/bin/convert"



/*
 * Paths to some virus scanners
 */
#define	_PATH_ANTIVIR	""
#define	_PATH_FPROT	""
#define	_PATH_UVSCAN	""
#define	_PATH_CLAMAV	""


/*
 * File transfer protocols
 */
#define	_PATH_RB	""
#define	_PATH_SB	""
#define	_PATH_RZ	""
#define	_PATH_SZ	""



/*
 * GoldED
 */
#define	_PATH_GOLDED	""
#define	_PATH_GOLDNODE	""

